server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端实例名称 单机版
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己本身就是注册中心，我的职责就是维护服务实例,并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://eureka7002.com:7002/eureka/ #在其它Eureka Server上注册(多个Eureka Server之间需要相互注册)
      defaultZone: http://eureka7001.com:7001/eureka/ #单机
  server:
    #关闭自我保护机制，保证不可用服务被及时剔除  默认为true开启
    #enable-self-preservation: false
    #设置剔除Eureka客户端服务超时时间间隔(单位毫秒)
    #eviction-interval-timer-in-ms: 2000
